### ISSUE TITLE
The browser does not work correctly using enlightenment window manager.

### ISSUE THREAD

**Issue by rda0** [sidus-dev/poseidon#10]
The initial tab works. Any new browser tab does nothing when I press enter (see errors).
The window and menus look strange (see screenshot), window is not resizable.

`✔maedersv@snidget:/opt/poseidon-browser-git🍺 ./poseidon

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5

(poseidon.py:2602): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -5
Traceback (most recent call last):
  File "./poseidon.py", line 1583, in on_load_url
    if is_url_valid(format, self.tlsbool, self.p_req()): page.webview.load_uri(format)
  File "./poseidon.py", line 2315, in p_req
    if db[0] == str(2): return db
TypeError: 'NoneType' object is not subscriptable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_poseidon-browser-git_poseidon.py.11599.crash'

Original exception was:
Traceback (most recent call last):
  File "./poseidon.py", line 1583, in on_load_url
    if is_url_valid(format, self.tlsbool, self.p_req()): page.webview.load_uri(format)
  File "./poseidon.py", line 2315, in p_req
    if db[0] == str(2): return db
TypeError: 'NoneType' object is not subscriptable`

![shot-2017-06-22_07-39-59](https://user-images.githubusercontent.com/6731714/27419045-0df503b8-571f-11e7-9997-2e8fdc3b93d3.jpg)

**Comment by sidus-dev** [comment]
Thanks for the report. Please check out the new version 0.6.5, it should solve your issue.

**Comment by rda0** [comment]
Thanks, that fixed the issue with the tab.

**Comment by sidus-dev** [comment]
I am trying now to reproduce the "weird look" issue in Ubuntu, at first sight it seems a theme related problem but not 100% sure. I have been able to test Poseidon on XFCE, Openbox and Gnome and themes like Adwaita, Arc, Breeze or Vertex, fits just well. I'll leave this issue open until I get some more info.

**Comment by rda0** [comment]
I tested the browser on a fresh installed Xenial machine using GNOME, LXDE and Xfce and several themes. It looks everywhere the same. I was just confused, because the title bar looks huge compared to my other apps and your [screenshot](https://raw.githubusercontent.com/sidus-dev/screenshots/master/poseidon-0.6.3.png). Maybe I just have to modify some theme css files to make it appear smaller and suit my minimalist UI needs :)

![shot-2017-06-27_11-11-43](https://user-images.githubusercontent.com/6731714/27580509-17dfa616-5b2b-11e7-987d-cf106c74d8c8.jpg)
